version: "3.9"
service:
  app:
    image: mcr.microsoft.com/devcontainers/go:0-1-bullseye
    volumes:
      - ../:/workspaces/app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:another-service
  nats:
    image: nats:2.9-linux
  